feat(404): add new 404 page
discord-docs/ddocs pull request #30
Opened 2022-02-02 14:40 UTC by lhjt

This PR adds the 404 page on the Figma document.

<img width="2168" alt="Screen Shot 2022-02-03 at 01 33 46" src="https://user-images.githubusercontent.com/48422312/152174512-a9fd17f9-3ca9-491b-9898-a2daee498210.png">

Instead of using white for the `Return to home` link as on the Figma, I chose to go with the current brand colour (#5865f2), as making the link white without any text decoration may obscure the fact that it is a link.

I'm not sure if we want to keep the link colour as it is, as the contrast for it is a little too low:

![2022-02-03T013411 FS](https://user-images.githubusercontent.com/48422312/152174878-98693001-1cfe-49fa-bb5a-266b551c96ef.png)

2022-02-02 15:49 UTC, MeguminSama requested changes
Would you be able to move wumpus behind the text? Sizing will be changed once we start putting mobile support in, but I think it would be good to make sure it doesn't cover any text.

![image](https://user-images.githubusercontent.com/27697325/152187747-f29b0aa3-9cac-433b-be43-1eb36c5c91cb.png)

2022-02-02 16:29 UTC, MeguminSama approved these changes

2022-02-02 18:47 UTC, quinchs approved these changes

2022-02-03 04:00 UTC, Liege72 approved these changes

2022-02-03 05:44 UTC, merged